extends: standard
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
env:
  es6: true
  browser: true
parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    ts: true
globals:
  describe: false
  it: false
  beforeEach: false
  afterEach: false
  beforeAll: false
  afterAll: false
  jasmine: false
