extends:
  - standard
  - plugin:@typescript-eslint/recommended
plugins:
  - "@typescript-eslint"

parser: "@typescript-eslint/parser"
rules:
  "@typescript-eslint/explicit-function-return-type": off
env:
  es6: true
  node: true
parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    ts: true
globals:
  describe: false
  it: false
  beforeEach: false
  afterEach: false
  beforeAll: false
  afterAll: false
  jasmine: false
  expect: false
  jest: false