language: node_js
node_js:
  - '8'
  - '10'
install:
  - yarn install
script:
  - yarn run lint
  - yarn test
  - yarn run build
deploy:
  provider: npm
  email: 'info@wp-kyoto.net'
  api_key: $NPM_TOKEN
  on:
    tags: true